google:
  project-id: ${GOOGLE_PROJECT-ID}
  client-id: ${GOOGLE_CLIENT-ID}
quarkus:
  hibernate-orm:
    database:
      generation: none
    scripts:
      generation: none
  flyway:
    migrate-at-start: true
  rest-client:
    logging:
      scope: request-response
    words-api:
      uri: ${WORDS_API_RAPID_API_URI}
      headers:
        x-rapidapi-host: ${WORDS_API_RAPID_API_HOST}
        x-rapidapi-key: ${WORDS_API_RAPID_API_KEY}
    lingua-robot:
      uri: ${LR_RAPID_API_URI}
      headers:
        x-rapidapi-host: ${LR_RAPID_API_HOST}
        x-rapidapi-key: ${LR_RAPID_API_KEY}
"%dev":
  quarkus:
    log:
      category:
        words-api:
          level: DEBUG
      level: INFO

    smallrye-jwt:
      enabled: true
    flyway:
      migrate-at-start: true
    datasource:
      devservices:
        enabled: false
      db-kind: ${DATABASE_DB-KIND:postgresql}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      jdbc:
        url: ${DATABASE_URL}

"%prod":
  quarkus:
    http:
      access-log:
        enabled: true
    smallrye-jwt:
      enabled: true
    datasource:
      devservices:
        enabled: false
      db-kind: ${DATABASE_DB-KIND:postgresql}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      jdbc:
        url: ${DATABASE_URL}
  smallrye:
    jwt:
      verify:
        key:
          location: /deployments/publicKey.pem
      sign:
        key:
          location: /deployments/privateKey.pem
